FROM node:18-alpine AS build

WORKDIR /app

COPY ./sentinel-dashboard/package.json ./
COPY ./sentinel-dashboard/package-lock.json ./

RUN npm install --include=dev

COPY ./sentinel-dashboard/ ./

RUN npm run build

FROM nginx:1.25-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
