# Optimized to cache pip packages
FROM python:3.9-slim

WORKDIR /app

# 1. Copy only requirements to leverage Docker cache
COPY requirements.txt .
# 2. Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copy the rest of the application code
COPY . .

CMD ["python", "calls_processing.py"]