services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "api" ]
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - DOCKER_ENV=true
    volumes:
      - ./data:/app/data
    ports:
      - "8001:8001"
    networks:
      - idx_agent_net

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "ui" ]
    depends_on:
      - api
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://api:8001
      - STREAMLIT_SERVER_PORT=8502
      - DOCKER_ENV=true
    ports:
      - "8502:8502"
    networks:
      - idx_agent_net

networks:
  idx_agent_net:
    driver: bridge
